# -*- mode: dockerfile -*-

FROM alpine:latest

RUN apk add \
    autoconf \
    autoconf-archive \
    automake \
    bash \
    bash-completion \
    ccache \
    ccmake \
    cmake \
    cmake-bash-completion \
    cmake-extras \
    coreutils \
    curl \
    doxygen \
    gawk \
    git \
    git-bash-completion \
    gpg \
    make \
    mercurial \
    mercurial-bash-completion \
    mercurial-chg \
    mercurial-pyc \
    meson \
    meson-bash-completion \
    meson-pyc \
    pacman \
    pacman-bash-completion \
    patch \
    patchutils \
    sudo \
    vim \
    wget \
    which

# Enable ccache.
RUN ln -s /usr/bin/ccache /usr/local/bin/powerpc-eabi-c++
RUN ln -s /usr/bin/ccache /usr/local/bin/powerpc-eabi-cc
RUN ln -s /usr/bin/ccache /usr/local/bin/powerpc-eabi-cpp
RUN ln -s /usr/bin/ccache /usr/local/bin/powerpc-eabi-g++
RUN ln -s /usr/bin/ccache /usr/local/bin/powerpc-eabi-gcc
RUN ln -s /usr/bin/ccache /usr/local/bin/powerpc-eabi-ld

RUN pacman-key --init
# Add WinterMute's key.
RUN pacman-key --recv BC26F752D25B92CE272E0F44F7FD5492264BB9D0 --keyserver keyserver.ubuntu.com
RUN pacman-key --lsign BC26F752D25B92CE272E0F44F7FD5492264BB9D0
# Add fincs' key.
RUN pacman-key --recv 62C7609ADA219C60 --keyserver keyserver.ubuntu.com
RUN pacman-key --lsign 62C7609ADA219C60

RUN pacman -U --noconfirm https://pkg.devkitpro.org/devkitpro-keyring.pkg.tar.zst

RUN echo "Color" >> /etc/pacman.conf
RUN echo "[dkp-libs]" >> /etc/pacman.conf
RUN echo "Server = https://pkg.devkitpro.org/packages" >> /etc/pacman.conf
RUN echo "[dkp-linux-musl]" >> /etc/pacman.conf
RUN echo 'Server = https://pkg.devkitpro.org/packages/linux-musl/$arch/' >> /etc/pacman.conf

RUN pacman -Syyu --noconfirm

RUN pacman -S --noconfirm wiiu-dev
# Remove devkit-env, it messes up PATH.
RUN pacman -R --noconfirm devkit-env
# Install the rest of the Wii U packages.
RUN pacman -S --noconfirm \
    dkp-meson-scripts \
    dkp-toolchain-vars \
    ppc-dev \
    ppc-portlibs \
    wiiu-portlibs
# Install SDL2 libs.
RUN pacman -S --noconfirm wiiu-sdl2-libs

# Clear pacman cache.
RUN pacman --noconfirm -Scc

# Create a regular user, no password.
RUN adduser -u 1000 user -D

# Allow this user to sudo with no password.
RUN echo "user	ALL=(ALL)	NOPASSWD: ALL" >> /etc/sudoers

USER user

ENV DEVKITPRO="/opt/devkitpro"
ENV DEVKITPPC="$DEVKITPRO/devkitPPC"
# Note: portlibs/wiiu takes precedence. Always append, to allow ccache to work.
ENV PATH="$PATH:$DEVKITPRO/portlibs/wiiu/bin:$DEVKITPRO/portlibs/ppc/bin:$DEVKITPPC/bin"

WORKDIR /home/user/src
